Refactoring to use a HookManager class
feathersjs/hooks pull request #32
Opened 2020-03-28 17:39 UTC by daffl

This is a refactoring that addresses performance and API improvements.

- Closes #22 
- Closes #28
- Closes #29

2020-03-30 08:33 UTC, bertho-zero requested changes
We can also add a test for that:

```js
console.log(customContext.hasOwnProperty('message')); // true
console.log(customContext.hasOwnProperty('arguments')); // true
console.log(customContext.hasOwnProperty('name')); // false
console.log(Object.keys(customContext)); // [ 'message', 'arguments', 'result' ]
console.log(JSON.stringify(customContext)); // {"message":"Custom message","arguments":["Changed",{}],"result":"Hello Changed"}
```

There is always a problem with the named parameters, We cannot copy getter/setter properties from the prototype to the instance. No worries about the props.

Stackoverflow: https://stackoverflow.com/questions/6039676/copying-javascript-getters-setters-to-another-prototype-object

UPDATE: Works fine:

```js
for (const key in ctx) {
  const getter = ctx.constructor.prototype.__lookupGetter__(key);

  if (getter) {
    ctx.__defineGetter__(key, getter);
    ctx.__defineSetter__(key, ctx.constructor.prototype.__lookupSetter__(key));
  } else {
    ctx[key] = ctx[key];
  }
}
```

2020-03-30 08:33 UTC, bertho-zero commented on packages/hooks/src/index.ts
> +  if (typeof target === 'function' && _hooks instanceof HookManager) {
```suggestion
  if (typeof target === 'function' && (_hooks instanceof HookManager || Array.isArray(_hooks))) {
```

In tests there is not one that accepts an array of hooks, without being wrapped beforehand:

```js
const sayHi = hooks(hello, [
  async (context, next) => {
    await next();
    context.result += '!';
  }
]);
```

2020-03-30 15:26 UTC, bertho-zero approved these changes

2020-03-30 15:31 UTC, bertho-zero commented
Note: wrapping an array of hooks with a `middleware` call is only useful if you chain with `.params` or `.props`

2020-04-05 21:23 UTC, merged

2020-04-05 21:25 UTC, daffl commented
This has been published as `v0.5.0-alpha.0`. I think it's still missing default parameter initialization but wondering if it could just be combined with `.props(object|initFunction)`.